- name: Install NodeJS
  apt:
    name: ['nodejs', 'npm']
  tags:
  - node
- name: Install n Node manager
  npm:
    name: n
    global: true
  tags:
  - node
- name: Select NodeJS version 14
  shell: n 14
  tags:
  - node
